### ISSUE TITLE
Simple Workflow

### ISSUE THREAD

**Issue by keyman015** [0x3F-Lab/clock-in-system#14]
## Description
Add automation into the workflow to improve code quality and productivity through automatic issue creation and linting.

## To-do
- [ ] Add github bot to automatically generate issues on assigned issues.
- [ ] Add linting workflow to auto-lint code.
- [ ] Add testing workflow to run project tests.
